### ISSUE TITLE
UI's static files are not found

### ISSUE THREAD

**Issue by pheyvaer** [gwu-libraries/sfm-docker#37]
Hi,

I have issues with serving the static files. There are not found when browsing to the UI. When I browse to the path `/ui/` I get the page, but the additional resources are not found (404): CSS, JavaScript, images. 
When doing `docker-compose logs -f` I see
```
ui_1                            | WARNING 2021-12-01 07:36:09,789 87 django.request Not Found: /static/ui/css/main.css
ui_1                            | WARNING 2021-12-01 07:36:09,791 87 django.server "GET /static/ui/css/main.css HTTP/1.1" 404 77
```
The host name and port are configured to a public IP and that access works. I've tried it with v2.4.0 and v2.5.0.
Any ideas what could be wrong?

**Comment by dolsysmith** [comment]
Hi @pheyvaer, 

Can you say more about your environment? And are you using the production template (`example.prod.docker-compose.yml`), and if so, are you using the `nginx-proxy` container? Not sure that would have anything to do with it, but I can't immediately think of what else might be causing that. 

And I'm assuming the `SFM_HOSTNAME` variable is set correctly in your `.env`, since you are able to see the UI, but you might double check that, too.

**Comment by pheyvaer** [comment]
Hi @dolsysmith 

I started first with `example.docker-compose.yml`, but now tried with `example.prod.docker-compose.yml` and that works (v2.5.0)! What is the big difference between these files? Does it look for the static files somewhere else?

**Comment by dolsysmith** [comment]
`example.docker-compose.yml` is used for development. (We should probably rename it to `example.dev.docker-compose.yml`.) It includes lines for bind-mounting external volumes to the containers where local copies of the code reside. Also relevant is the `UI_TAG` variable in `.env`, which determines whether the app uses Apache as the webserver or Django's default webserver. (The latter is useful for development because it automatically reloads changes to the code.) If you're interested in doing development, make sure you follow the Developer instructions for set up in the [SFM documentation](https://sfm.readthedocs.io/en/latest/development.html).

**Comment by pheyvaer** [comment]
Thanks for the info!
